-- AUTOGENERATED FILE --
-- https://harmboschloo.github.io/elm-ecs-generator/ui/#%7B%22ecs%22%3A%5B%22Ecs%22%2C%22Ecs%22%5D%2C%22components%22%3A%5B%5B%22Components%22%2C%22Bounce%22%5D%2C%5B%22Components%22%2C%22Color%22%5D%2C%5B%22Components%22%2C%22Position%22%5D%2C%5B%22Components%22%2C%22Teleport%22%5D%2C%5B%22Components%22%2C%22Velocity%22%5D%5D%7D


module Ecs exposing
    ( Ecs, empty
    , EntityId, create, destroy, reset, size, activeSize, idToInt, intToId
    , ComponentType, get, insert, update, remove
    , iterate, iterate2, iterate3, iterate4, iterate5
    , bounceComponent, colorComponent, positionComponent, teleportComponent, velocityComponent
    )

{-| Your Entitiy-Component-System.


# Model

@docs Ecs, empty


# Entities

@docs EntityId, create, destroy, reset, size, activeSize, idToInt, intToId


# Components

@docs ComponentType, get, insert, update, remove


# Iterate Entities

@docs iterate, iterate2, iterate3, iterate4, iterate5


# Your Component Types

@docs bounceComponent, colorComponent, positionComponent, teleportComponent, velocityComponent

-}

import Components
import Dict



-- MODEL --


{-| -}
type Ecs
    = Ecs Model


type alias Model =
    { bounceComponents : Dict.Dict Int Components.Bounce
    , colorComponents : Dict.Dict Int Components.Color
    , positionComponents : Dict.Dict Int Components.Position
    , teleportComponents : Dict.Dict Int Components.Teleport
    , velocityComponents : Dict.Dict Int Components.Velocity
    , numberOfCreatedEntities : Int
    , destroyedEntities : List Int
    }


{-| -}
empty : Ecs
empty =
    Ecs
        { bounceComponents = Dict.empty
        , colorComponents = Dict.empty
        , positionComponents = Dict.empty
        , teleportComponents = Dict.empty
        , velocityComponents = Dict.empty
        , numberOfCreatedEntities = 0
        , destroyedEntities = []
        }



-- ENTITIES --


{-| -}
type EntityId
    = EntityId Int


{-| -}
create : Ecs -> ( Ecs, EntityId )
create (Ecs model) =
    case model.destroyedEntities of
        [] ->
            ( Ecs { model | numberOfCreatedEntities = model.numberOfCreatedEntities + 1 }
            , EntityId model.numberOfCreatedEntities
            )

        head :: tail ->
            ( Ecs { model | destroyedEntities = tail }
            , EntityId head
            )


{-| -}
destroy : EntityId -> Ecs -> Ecs
destroy (EntityId entityId) (Ecs model) =
    { model | destroyedEntities = entityId :: model.destroyedEntities }
        |> resetEntity entityId
        |> Ecs


{-| -}
reset : EntityId -> Ecs -> Ecs
reset (EntityId entityId) (Ecs model) =
    Ecs (resetEntity entityId model)


resetEntity : Int -> Model -> Model
resetEntity entityId model =
    { model
        | bounceComponents = Dict.remove entityId model.bounceComponents
        , colorComponents = Dict.remove entityId model.colorComponents
        , positionComponents = Dict.remove entityId model.positionComponents
        , teleportComponents = Dict.remove entityId model.teleportComponents
        , velocityComponents = Dict.remove entityId model.velocityComponents
    }


{-| -}
size : Ecs -> Int
size (Ecs model) =
    model.numberOfCreatedEntities


{-| -}
activeSize : Ecs -> Int
activeSize (Ecs model) =
    model.numberOfCreatedEntities - List.length model.destroyedEntities


{-| -}
idToInt : EntityId -> Int
idToInt (EntityId id) =
    id


{-| -}
intToId : Int -> Ecs -> Maybe EntityId
intToId id ecs =
    if id < size ecs then
        Just (EntityId id)

    else
        Nothing



-- COMPONENTS --


{-| -}
type ComponentType a
    = ComponentType
        { getComponents : Model -> Dict.Dict Int a
        , setComponents : Dict.Dict Int a -> Model -> Model
        }


{-| -}
get : EntityId -> ComponentType a -> Ecs -> Maybe a
get (EntityId entityId) (ComponentType { getComponents }) (Ecs model) =
    Dict.get entityId (getComponents model)


{-| -}
insert : EntityId -> ComponentType a -> a -> Ecs -> Ecs
insert (EntityId entityId) (ComponentType componentType) component (Ecs model) =
    Ecs
        (componentType.setComponents
            (Dict.insert entityId component (componentType.getComponents model))
            model
        )


{-| -}
update : EntityId -> ComponentType a -> (Maybe a -> Maybe a) -> Ecs -> Ecs
update (EntityId entityId) (ComponentType componentType) updater (Ecs model) =
    Ecs
        (componentType.setComponents
            (Dict.update entityId updater (componentType.getComponents model))
            model
        )


{-| -}
remove : EntityId -> ComponentType a -> Ecs -> Ecs
remove (EntityId entityId) (ComponentType componentType) (Ecs model) =
    Ecs
        (componentType.setComponents
            (Dict.remove entityId (componentType.getComponents model))
            model
        )



-- ITERATE ENTITIES --


{-| -}
iterate :
    ComponentType a
    -> (EntityId -> a -> ( Ecs, x ) -> ( Ecs, x ))
    -> ( Ecs, x )
    -> ( Ecs, x )
iterate (ComponentType componentType) callback ( Ecs model, x ) =
    Dict.foldl
        (EntityId >> callback)
        ( Ecs model, x )
        (componentType.getComponents model)


{-| -}
iterate2 :
    ComponentType c1
    -> ComponentType c2
    -> (EntityId -> c1 -> c2 -> ( Ecs, x ) -> ( Ecs, x ))
    -> ( Ecs, x )
    -> ( Ecs, x )
iterate2 (ComponentType type1) (ComponentType type2) callback ( Ecs model, x ) =
    let
        components1 =
            type1.getComponents model

        components2 =
            type2.getComponents model
    in
    Dict.foldl
        (\entityId component1 result ->
            callback (EntityId entityId) component1
                |> next entityId components2
                |> Maybe.map ((|>) result)
                |> Maybe.withDefault result
        )
        ( Ecs model, x )
        components1


{-| -}
iterate3 :
    ComponentType c1
    -> ComponentType c2
    -> ComponentType c3
    -> (EntityId -> c1 -> c2 -> c3 -> ( Ecs, x ) -> ( Ecs, x ))
    -> ( Ecs, x )
    -> ( Ecs, x )
iterate3 (ComponentType type1) (ComponentType type2) (ComponentType type3) callback ( Ecs model, x ) =
    let
        components1 =
            type1.getComponents model

        components2 =
            type2.getComponents model

        components3 =
            type3.getComponents model
    in
    Dict.foldl
        (\entityId component1 result ->
            callback (EntityId entityId) component1
                |> next entityId components2
                |> Maybe.andThen (next entityId components3)
                |> Maybe.map ((|>) result)
                |> Maybe.withDefault result
        )
        ( Ecs model, x )
        components1


{-| -}
iterate4 :
    ComponentType c1
    -> ComponentType c2
    -> ComponentType c3
    -> ComponentType c4
    -> (EntityId -> c1 -> c2 -> c3 -> c4 -> ( Ecs, x ) -> ( Ecs, x ))
    -> ( Ecs, x )
    -> ( Ecs, x )
iterate4 (ComponentType type1) (ComponentType type2) (ComponentType type3) (ComponentType type4) callback ( Ecs model, x ) =
    let
        components1 =
            type1.getComponents model

        components2 =
            type2.getComponents model

        components3 =
            type3.getComponents model

        components4 =
            type4.getComponents model
    in
    Dict.foldl
        (\entityId component1 result ->
            callback (EntityId entityId) component1
                |> next entityId components2
                |> Maybe.andThen (next entityId components3)
                |> Maybe.andThen (next entityId components4)
                |> Maybe.map ((|>) result)
                |> Maybe.withDefault result
        )
        ( Ecs model, x )
        components1


{-| -}
iterate5 :
    ComponentType c1
    -> ComponentType c2
    -> ComponentType c3
    -> ComponentType c4
    -> ComponentType c5
    -> (EntityId -> c1 -> c2 -> c3 -> c4 -> c5 -> ( Ecs, x ) -> ( Ecs, x ))
    -> ( Ecs, x )
    -> ( Ecs, x )
iterate5 (ComponentType type1) (ComponentType type2) (ComponentType type3) (ComponentType type4) (ComponentType type5) callback ( Ecs model, x ) =
    let
        components1 =
            type1.getComponents model

        components2 =
            type2.getComponents model

        components3 =
            type3.getComponents model

        components4 =
            type4.getComponents model

        components5 =
            type5.getComponents model
    in
    Dict.foldl
        (\entityId component1 result ->
            callback (EntityId entityId) component1
                |> next entityId components2
                |> Maybe.andThen (next entityId components3)
                |> Maybe.andThen (next entityId components4)
                |> Maybe.andThen (next entityId components5)
                |> Maybe.map ((|>) result)
                |> Maybe.withDefault result
        )
        ( Ecs model, x )
        components1


next : Int -> Dict.Dict Int a -> (a -> b) -> Maybe b
next entityId components callback =
    Dict.get entityId components |> Maybe.map callback



-- YOUR COMPONENT TYPES --


{-| -}
bounceComponent : ComponentType Components.Bounce
bounceComponent =
    ComponentType
        { getComponents = .bounceComponents
        , setComponents = \components model -> { model | bounceComponents = components }
        }


{-| -}
colorComponent : ComponentType Components.Color
colorComponent =
    ComponentType
        { getComponents = .colorComponents
        , setComponents = \components model -> { model | colorComponents = components }
        }


{-| -}
positionComponent : ComponentType Components.Position
positionComponent =
    ComponentType
        { getComponents = .positionComponents
        , setComponents = \components model -> { model | positionComponents = components }
        }


{-| -}
teleportComponent : ComponentType Components.Teleport
teleportComponent =
    ComponentType
        { getComponents = .teleportComponents
        , setComponents = \components model -> { model | teleportComponents = components }
        }


{-| -}
velocityComponent : ComponentType Components.Velocity
velocityComponent =
    ComponentType
        { getComponents = .velocityComponents
        , setComponents = \components model -> { model | velocityComponents = components }
        }
