module Ecs.Entity42 exposing (entity, components)

{-| ECS entities with 42 components.
-}

import Ecs.Internal exposing (ComponentSpec(..), EntitySpec(..))


{-| -}
entity :
    (Maybe component1 -> Maybe component2 -> Maybe component3 -> Maybe component4 -> Maybe component5 -> Maybe component6 -> Maybe component7 -> Maybe component8 -> Maybe component9 -> Maybe component10 -> Maybe component11 -> Maybe component12 -> Maybe component13 -> Maybe component14 -> Maybe component15 -> Maybe component16 -> Maybe component17 -> Maybe component18 -> Maybe component19 -> Maybe component20 -> Maybe component21 -> Maybe component22 -> Maybe component23 -> Maybe component24 -> Maybe component25 -> Maybe component26 -> Maybe component27 -> Maybe component28 -> Maybe component29 -> Maybe component30 -> Maybe component31 -> Maybe component32 -> Maybe component33 -> Maybe component34 -> Maybe component35 -> Maybe component36 -> Maybe component37 -> Maybe component38 -> Maybe component39 -> Maybe component40 -> Maybe component41 -> Maybe component42 -> components)
    -> EntitySpec components
entity createComponents =
    EntitySpec { empty = createComponents Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing Nothing }


{-| -}
components :
    (ComponentSpec components component1 -> ComponentSpec components component2 -> ComponentSpec components component3 -> ComponentSpec components component4 -> ComponentSpec components component5 -> ComponentSpec components component6 -> ComponentSpec components component7 -> ComponentSpec components component8 -> ComponentSpec components component9 -> ComponentSpec components component10 -> ComponentSpec components component11 -> ComponentSpec components component12 -> ComponentSpec components component13 -> ComponentSpec components component14 -> ComponentSpec components component15 -> ComponentSpec components component16 -> ComponentSpec components component17 -> ComponentSpec components component18 -> ComponentSpec components component19 -> ComponentSpec components component20 -> ComponentSpec components component21 -> ComponentSpec components component22 -> ComponentSpec components component23 -> ComponentSpec components component24 -> ComponentSpec components component25 -> ComponentSpec components component26 -> ComponentSpec components component27 -> ComponentSpec components component28 -> ComponentSpec components component29 -> ComponentSpec components component30 -> ComponentSpec components component31 -> ComponentSpec components component32 -> ComponentSpec components component33 -> ComponentSpec components component34 -> ComponentSpec components component35 -> ComponentSpec components component36 -> ComponentSpec components component37 -> ComponentSpec components component38 -> ComponentSpec components component39 -> ComponentSpec components component40 -> ComponentSpec components component41 -> ComponentSpec components component42 -> componentSpecs)
    -> (Maybe component1 -> Maybe component2 -> Maybe component3 -> Maybe component4 -> Maybe component5 -> Maybe component6 -> Maybe component7 -> Maybe component8 -> Maybe component9 -> Maybe component10 -> Maybe component11 -> Maybe component12 -> Maybe component13 -> Maybe component14 -> Maybe component15 -> Maybe component16 -> Maybe component17 -> Maybe component18 -> Maybe component19 -> Maybe component20 -> Maybe component21 -> Maybe component22 -> Maybe component23 -> Maybe component24 -> Maybe component25 -> Maybe component26 -> Maybe component27 -> Maybe component28 -> Maybe component29 -> Maybe component30 -> Maybe component31 -> Maybe component32 -> Maybe component33 -> Maybe component34 -> Maybe component35 -> Maybe component36 -> Maybe component37 -> Maybe component38 -> Maybe component39 -> Maybe component40 -> Maybe component41 -> Maybe component42 -> components)
    -> (components -> Maybe component1)
    -> (components -> Maybe component2)
    -> (components -> Maybe component3)
    -> (components -> Maybe component4)
    -> (components -> Maybe component5)
    -> (components -> Maybe component6)
    -> (components -> Maybe component7)
    -> (components -> Maybe component8)
    -> (components -> Maybe component9)
    -> (components -> Maybe component10)
    -> (components -> Maybe component11)
    -> (components -> Maybe component12)
    -> (components -> Maybe component13)
    -> (components -> Maybe component14)
    -> (components -> Maybe component15)
    -> (components -> Maybe component16)
    -> (components -> Maybe component17)
    -> (components -> Maybe component18)
    -> (components -> Maybe component19)
    -> (components -> Maybe component20)
    -> (components -> Maybe component21)
    -> (components -> Maybe component22)
    -> (components -> Maybe component23)
    -> (components -> Maybe component24)
    -> (components -> Maybe component25)
    -> (components -> Maybe component26)
    -> (components -> Maybe component27)
    -> (components -> Maybe component28)
    -> (components -> Maybe component29)
    -> (components -> Maybe component30)
    -> (components -> Maybe component31)
    -> (components -> Maybe component32)
    -> (components -> Maybe component33)
    -> (components -> Maybe component34)
    -> (components -> Maybe component35)
    -> (components -> Maybe component36)
    -> (components -> Maybe component37)
    -> (components -> Maybe component38)
    -> (components -> Maybe component39)
    -> (components -> Maybe component40)
    -> (components -> Maybe component41)
    -> (components -> Maybe component42)
    -> componentSpecs
components createComponentSpecs createComponents get1 get2 get3 get4 get5 get6 get7 get8 get9 get10 get11 get12 get13 get14 get15 get16 get17 get18 get19 get20 get21 get22 get23 get24 get25 get26 get27 get28 get29 get30 get31 get32 get33 get34 get35 get36 get37 get38 get39 get40 get41 get42 =
    createComponentSpecs
        (ComponentSpec
            { getComponent = get1
            , setComponent =
                \component data ->
                    createComponents
                        component
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get2
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        component
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get3
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        component
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get4
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        component
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get5
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        component
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get6
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        component
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get7
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        component
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get8
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        component
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get9
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        component
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get10
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        component
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get11
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        component
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get12
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        component
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get13
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        component
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get14
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        component
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get15
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        component
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get16
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        component
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get17
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        component
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get18
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        component
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get19
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        component
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get20
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        component
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get21
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        component
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get22
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        component
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get23
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        component
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get24
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        component
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get25
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        component
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get26
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        component
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get27
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        component
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get28
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        component
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get29
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        component
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get30
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        component
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get31
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        component
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get32
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        component
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get33
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        component
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get34
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        component
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get35
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        component
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get36
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        component
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get37
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        component
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get38
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        component
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get39
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        component
                        (get40 data)
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get40
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        component
                        (get41 data)
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get41
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        component
                        (get42 data)
            }
        )
        (ComponentSpec
            { getComponent = get42
            , setComponent =
                \component data ->
                    createComponents
                        (get1 data)
                        (get2 data)
                        (get3 data)
                        (get4 data)
                        (get5 data)
                        (get6 data)
                        (get7 data)
                        (get8 data)
                        (get9 data)
                        (get10 data)
                        (get11 data)
                        (get12 data)
                        (get13 data)
                        (get14 data)
                        (get15 data)
                        (get16 data)
                        (get17 data)
                        (get18 data)
                        (get19 data)
                        (get20 data)
                        (get21 data)
                        (get22 data)
                        (get23 data)
                        (get24 data)
                        (get25 data)
                        (get26 data)
                        (get27 data)
                        (get28 data)
                        (get29 data)
                        (get30 data)
                        (get31 data)
                        (get32 data)
                        (get33 data)
                        (get34 data)
                        (get35 data)
                        (get36 data)
                        (get37 data)
                        (get38 data)
                        (get39 data)
                        (get40 data)
                        (get41 data)
                        component
            }
        )
