module EcsGenerator.Generate exposing (generate)

import EcsGenerator.CodeBuilder as Builder exposing (Document)
import EcsGenerator.Config as Config exposing (Component, Config, Iterator)
import EcsGenerator.Utils as Utils
import Url exposing (percentEncode)


generate : Config -> String
generate config =
    let
        topComment =
            "-- AUTOGENERATED FILE --\n"
                ++ "-- https://harmboschloo.github.io/elm-ecs-generator/#"
                ++ (Config.encodeString >> percentEncode) config
    in
    Builder.document (Config.ecsModuleName config.ecs) topComment
        |> generateComponentImports config
        |> generateApi config
        |> generateEntityIterators config
        |> generateEntitySetTypes config
        |> generateComponentTypes config
        |> Builder.replace "{Ecs}" (Config.ecsTypeName config.ecs)
        |> Builder.toString


generateComponentImports : Config -> Document -> Document
generateComponentImports { components } document =
    List.foldl
        (\component ->
            Builder.imported (Config.componentModuleName component)
        )
        document
        components


generateApi : Config -> Document -> Document
generateApi { components, iterators } document =
    document
        |> Builder.imported "Array"
        |> Builder.imported "Set"
        |> Builder.comment "-- MODEL --"
        |> Builder.exposed "{Ecs}"
        |> Builder.declaration """
type {Ecs}
    = Ecs_ Model_
"""
        |> Builder.declaration
            ("""
type alias Model_ =
    { """
                ++ ([ List.map
                        (\component ->
                            componentsFieldName component
                                ++ " : Array.Array (Maybe "
                                ++ componentTypeReference component
                                ++ ")"
                        )
                        components
                    , List.map
                        (iteratorEntitiesFieldName
                            >> Utils.append " : Set.Set Int"
                        )
                        iterators
                    ]
                        |> List.concat
                        |> String.join "\n    , "
                   )
                ++ """
    , destroyedEntities_ : List Int
    }
"""
            )
        |> Builder.exposed "empty"
        |> Builder.declaration
            ("""
empty : {Ecs}
empty =
    Ecs_
        { """
                ++ ([ List.map
                        (componentsFieldName
                            >> Utils.append " = Array.empty"
                        )
                        components
                    , List.map
                        (iteratorEntitiesFieldName
                            >> Utils.append " = Set.empty"
                        )
                        iterators
                    ]
                        |> List.concat
                        |> String.join "\n        , "
                   )
                ++ """
        , destroyedEntities_ = []
        }
"""
            )
        |> Builder.comment "-- ENTITIES --"
        |> Builder.exposed "EntityId"
        |> Builder.declaration """
type EntityId
    = EntityId Int
"""
        |> Builder.exposed "createEntity"
        |> Builder.declaration
            ("""
createEntity : {Ecs} -> ( {Ecs}, EntityId )
createEntity (Ecs_ model_) =
    case model_.destroyedEntities_ of
        [] ->
            ( Ecs_
                { model_
                    | """
                ++ (List.map
                        (componentsFieldName
                            >> (\field ->
                                    field
                                        ++ " = Array.push Nothing model_."
                                        ++ field
                               )
                        )
                        components
                        |> String.join "\n                    , "
                   )
                ++ """
                }
            , EntityId (Array.length model_."""
                ++ (List.head components
                        |> Maybe.map componentsFieldName
                        |> Maybe.withDefault ""
                   )
                ++ """)
            )

        head_ :: tail_ ->
            ( Ecs_ { model_ | destroyedEntities_ = tail_ }
            , EntityId head_
            )
"""
            )
        |> Builder.exposed "destroyEntity"
        |> Builder.declaration """
destroyEntity : EntityId -> {Ecs} -> {Ecs}
destroyEntity (EntityId entityId_) (Ecs_ model_) =
    { model_ | destroyedEntities_ = entityId_ :: model_.destroyedEntities_ }
        |> removeEntityComponents_ entityId_
        |> Ecs_
"""
        |> Builder.exposed "resetEntity"
        |> Builder.declaration """
resetEntity : EntityId -> {Ecs} -> {Ecs}
resetEntity (EntityId entityId_) (Ecs_ model_) =
    Ecs_ (removeEntityComponents_ entityId_ model_)
"""
        |> Builder.declaration
            ("""
removeEntityComponents_ : Int -> Model_ -> Model_
removeEntityComponents_ entityId_ model_ =
    { model_
        | """
                ++ ([ List.map
                        (componentsFieldName
                            >> (\field ->
                                    field
                                        ++ " = Array.set entityId_ Nothing model_."
                                        ++ field
                               )
                        )
                        components
                    , List.map
                        (iteratorEntitiesFieldName
                            >> (\field ->
                                    field
                                        ++ " = Set.remove entityId_ model_."
                                        ++ field
                               )
                        )
                        iterators
                    ]
                        |> List.concat
                        |> String.join "\n        , "
                   )
                ++ """
    }
"""
            )
        |> Builder.comment "-- COMPONENTS --"
        |> Builder.exposed "insertComponent"
        |> Builder.declaration """
insertComponent : EntityId -> ComponentType a -> a -> {Ecs} -> {Ecs}
insertComponent (EntityId entityId_) (ComponentType type_) component_ (Ecs_ model_) =
    let
        updatedModel_ =
            type_.setComponents
                (Array.set entityId_ (Just component_) (type_.getComponents model_))
                model_
    in
    Ecs_
        (List.foldl (insertEntityInSet_ entityId_) updatedModel_ type_.entitySets)
"""
        |> Builder.declaration """
insertEntityInSet_ : Int -> EntitySetType_ -> Model_ -> Model_
insertEntityInSet_ entityId_ entitySetType_ model_ =
    if entitySetType_.member entityId_ model_ then
        entitySetType_.setEntities
            (Set.insert entityId_ (entitySetType_.getEntities model_))
            model_

    else
        model_
"""
        |> Builder.exposed "removeComponent"
        |> Builder.declaration """
removeComponent : EntityId -> ComponentType a -> {Ecs} -> {Ecs}
removeComponent (EntityId entityId_) (ComponentType type_) (Ecs_ model_) =
    type_.entitySets
        |> List.foldl (removeEntityFromSet_ entityId_) model_
        |> type_.setComponents
            (Array.set entityId_ Nothing (type_.getComponents model_))
        |> Ecs_
"""
        |> Builder.declaration """
removeEntityFromSet_ : Int -> EntitySetType_ -> Model_ -> Model_
removeEntityFromSet_ entityId_ entitySetType_ model_ =
    entitySetType_.setEntities
        (Set.remove entityId_ (entitySetType_.getEntities model_))
        model_
"""
        |> Builder.exposed "getComponent"
        |> Builder.declaration """
getComponent : EntityId -> ComponentType a -> {Ecs} -> Maybe a
getComponent (EntityId entityId_) (ComponentType type_) (Ecs_ model_) =
    Array.get entityId_ (type_.getComponents model_)
        |> Maybe.withDefault Nothing
"""


generateEntityIterators : Config -> Document -> Document
generateEntityIterators { iterators } document =
    document
        |> Builder.comment "-- ENTITY ITERATORS --"
        |> (\doc ->
                List.foldl
                    generateEntityIterator
                    doc
                    iterators
           )
        |> Builder.declaration """
nextComponent_ : Array.Array (Maybe a) -> Int -> (a -> b) -> Maybe b
nextComponent_ components_ entityId_ callback_ =
    Array.get entityId_ components_
        |> Maybe.withDefault Nothing
        |> Maybe.map callback_
"""


generateEntityIterator : Iterator -> Document -> Document
generateEntityIterator iterator document =
    let
        name =
            iteratorVariableName iterator
    in
    document
        |> Builder.exposed name
        |> Builder.declaration
            (name
                ++ """ :
    (EntityId -> """
                ++ String.join " -> "
                    (Config.iteratorComponents iterator
                        |> List.map componentTypeReference
                    )
                ++ """ -> ( {Ecs}, context ) -> ( {Ecs}, context ))
    -> ( {Ecs}, context )
    -> ( {Ecs}, context )
"""
                ++ name
                ++ """ callback_ ( Ecs_ model_, context_ ) =
    Set.foldl
        (\\entityId_ result_ ->
            callback_ (EntityId entityId_)
                """
                ++ (List.indexedMap
                        (\index component ->
                            "|> "
                                ++ wrapNextComponent index
                                    ("nextComponent_ model_."
                                        ++ componentsFieldName component
                                        ++ " entityId_"
                                    )
                        )
                        (Config.iteratorComponents iterator)
                        |> String.join "\n                "
                   )
                ++ """
                |> Maybe.map ((|>) result_)
                |> Maybe.withDefault result_
        )
        ( Ecs_ model_, context_ )
        model_."""
                ++ iteratorEntitiesFieldName iterator
            )


wrapNextComponent : Int -> (String -> String)
wrapNextComponent index =
    if index == 0 then
        identity

    else
        \a -> "Maybe.andThen (" ++ a ++ ")"


generateEntitySetTypes : Config -> Document -> Document
generateEntitySetTypes { components, iterators } document =
    document
        |> Builder.comment "-- ENTITY SET TYPES --"
        |> Builder.declaration """
type alias EntitySetType_ =
    { getEntities : Model_ -> Set.Set Int
    , setEntities : Set.Set Int -> Model_ -> Model_
    , member : Int -> Model_ -> Bool
    }
"""
        |> (\doc -> List.foldl generateEntitySetType doc iterators)
        |> Builder.declaration """
isComponentsMember_ entityId_ components_ =
    case Array.get entityId_ components_ of
        Just (Just _) ->
            True

        _ ->
            False
"""


generateEntitySetType : Iterator -> Document -> Document
generateEntitySetType iterator document =
    let
        name =
            entitySetVariableName iterator

        entitiesModelField =
            iteratorEntitiesFieldName iterator
    in
    document
        |> Builder.declaration
            (name
                ++ " : EntitySetType_\n"
                ++ name
                ++ """ =
    { getEntities = ."""
                ++ entitiesModelField
                ++ """
    , setEntities = \\entities_ model_ -> { model_ | """
                ++ entitiesModelField
                ++ """ = entities_ }
    , member =
        \\entityId_ model_ ->
            """
                ++ (List.map
                        (componentsFieldName
                            >> (++) "isComponentsMember_ entityId_ model_."
                        )
                        (Config.iteratorComponents iterator)
                        |> String.join "\n                && "
                   )
                ++ """
    }
    """
            )


generateComponentTypes : Config -> Document -> Document
generateComponentTypes { components, iterators } document =
    document
        |> Builder.comment "-- COMPONENT TYPES --"
        |> Builder.exposed "ComponentType"
        |> Builder.declaration """
type ComponentType a
    = ComponentType
        { getComponents : Model_ -> Array.Array (Maybe a)
        , setComponents : Array.Array (Maybe a) -> Model_ -> Model_
        , entitySets : List EntitySetType_
        }
"""
        |> (\doc -> List.foldl (generateComponentType iterators) doc components)


generateComponentType : List Iterator -> Component -> Document -> Document
generateComponentType iterators component document =
    let
        typeName =
            componentTypeReference component

        modelField =
            componentsFieldName component

        name =
            Utils.firstToLower (Config.componentTypeName component)

        componentIterators =
            List.filter
                (Config.iteratorComponents >> List.member component)
                iterators
    in
    document
        |> Builder.exposed name
        |> Builder.declaration
            (name
                ++ " : ComponentType "
                ++ typeName
                ++ "\n"
                ++ name
                ++ """ =
    ComponentType
        { getComponents = ."""
                ++ modelField
                ++ """
        , setComponents = \\components_ model_ -> { model_ | """
                ++ modelField
                ++ """ = components_ }
        , entitySets = ["""
                ++ (List.map entitySetVariableName componentIterators
                        |> String.join ", "
                        |> padIfNotEmpty
                   )
                ++ """]
        }
"""
            )


padIfNotEmpty : String -> String
padIfNotEmpty string =
    if String.isEmpty string then
        string

    else
        " " ++ string ++ " "



-- HELPERS --


componentTypeReference : Component -> String
componentTypeReference component =
    Config.componentModuleName component
        ++ "."
        ++ Config.componentTypeName component


componentsFieldName : Component -> String
componentsFieldName =
    Config.componentTypeName
        >> Utils.firstToLower
        >> Utils.append "Components"


iteratorEntitiesFieldName : Iterator -> String
iteratorEntitiesFieldName =
    Config.iteratorName
        >> Utils.firstToLower
        >> Utils.append "Entities"


iteratorVariableName : Iterator -> String
iteratorVariableName =
    Config.iteratorName
        >> Utils.firstToUpper
        >> (++) "iterate"
        >> Utils.append "Entities"


entitySetVariableName : Iterator -> String
entitySetVariableName =
    Config.iteratorName
        >> Utils.firstToLower
        >> Utils.append "EntitySet_"
